### ISSUE TITLE
Drop down to .NET 4.5.1?

### ISSUE THREAD

**Issue by walro** [twingly/twingly-search-api-dotnet#21]
This would allow us to use the library with Mono, which would let us test on Travis CI and let us use the library in OSX. :)

I don't think we are using any [4.5.2 features](https://msdn.microsoft.com/en-us/library/ms171868(v=vs.110).aspx#v452) so it should be safe enough.

**Comment by jage** [comment]
Sure!

**Comment by walro** [comment]
I'll do 4.5, I can't find any information concerning Mono and official 4.5.1 support.

**Comment by walro** [comment]
Actually, this was interesting: https://github.com/aspnet/dnx/issues/374#issue-36381368 so I guess 4.5.1 is fine.
